############# English navigation ##############

# main menu
[[main]]
name = "Home"
pageRef = "/"
weight = 1

[[main]]
name = "About"
pageRef = "/about"
weight = 2

[[main]]
name = "Blog"
pageRef = "/blog"
weight = 3


[[main]]
name = "Categories"
pageRef = "/categories"
weight = 4

[[main]]
name = "Fiches Pratiques"
pageRef = "/fiches"
weight = 5

[[main]]
parent = "Fiches Pratiques"
name = "Méthodes"
pageRef = "/fiches/methods"

[[main]]
parent = "Fiches Pratiques"
name = "Outils"
pageRef = "/fiches/tools"

# footer menu
[[footer]]
name = "About"
pageRef = "/about"
weight = 1

[[footer]]
name = "Blog"
pageRef = "/blog"
weight = 2

[[footer]]
name = "Privacy Policy"
pageRef = "/privacy-policy"
weight = 3
